trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  GitVersion.SemVer: ''

steps:
- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: test
    publishTestResults: true
- task: UseGitVersion@5
  displayName: gitversion
  inputs:
    versionSpec: '5.x'
- task: DotNetCoreCLI@2
  displayName: dotnet pack
  inputs:
    command: pack
    arguments: '-p:PackageVersion=$(GitVersion.MajorMinorPatch)'
    packDirectory: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'package'
