trigger:
- master

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: test
    publishTestResults: true
- task: UseGitVersion@5
  displayName: gitversion
  inputs:
    versionSpec: '5.x'
- task: DotNetCoreCLI@2
  displayName: dotnet pack
  inputs:
    command: custom
    custom: 'pack'
    arguments: [ '-p:Version=$(GitVersion.SemVer)', ' -p:PackageVersion=$(GitVersion.SemVer)']
    packDirectory: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'package'
