trigger:
- master

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseGitVersion@5
  displayName: gitversion
  inputs:
    versionSpec: '5.x'
# - task: DotNetCoreCLI@2
#   displayName: dotnet build
#   inputs:
#     command: build
#     arguments: -p:Version=$(GitVersion.MajorMinorPatch)
- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: test
    arguments: -p:Version=$(GitVersion.MajorMinorPatch)
    publishTestResults: true
- task: DotNetCoreCLI@2
  displayName: dotnet pack
  inputs:
    command: pack
    nobuild: true
    versioningScheme: byEnvVar
    versionEnvVar: GitVersion.SemVer
    packDirectory: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'package'
